### ISSUE TITLE
VAD on short audio packet

### ISSUE THREAD

**Issue by eziolotta** [zhenghuatan/rVADfast#1]
Nice project !!
From my test, rVADfast performs good segmentation of a medium sized wav file ( > 10/15 seconds )
However, If we cut the input audio (ex: to 5 sec. ), the results are not the same, why is a _posteriori_ analysis done?

It would be nice to apply this library in realtime systems, where server analyzes audio stream, that is short packets of bit-audio in sequence.

**Comment by eziolotta** [comment]
This is my experiment with rVADFast:
https://github.com/MozillaItalia/DeepSpeech-Italian-Model/issues/107#issuecomment-770384647

**Comment by HolgerBovbjerg** [comment]
Hi,

For now, we are not considering streaming VAD use.
Not sure what is meant by, "why is a posteriori analysis done?". However, you can find explanations for the various design choices in rVAD in the corresponding research paper: https://arxiv.org/abs/1906.03588
