### ISSUE TITLE
Only Mono audio supported

### ISSUE THREAD

**Issue by AWAS666** [zhenghuatan/rVADfast#5]
This audiofile.read will return a different value depending if the audio is mono or stereo. It will return a two dimensional array on non mono audio which will then have the wrong size in the vad class itself.
https://github.com/zhenghuatan/rVADfast/blob/7f93168fe5acdbacad56e1567b2dcaf6210b0f07/src/rVADfast/process/process.py#L49

Using librosa would be one solution (though that'd require an additional dependency)

This would do the trick there though:
`waveform, sampling_rate = librosa.load(self.temp_file, mono=True, sr=None)`

**Comment by HolgerBovbjerg** [comment]
Hi,

Thanks for raising the issue.
In this case, would you like to perform VAD on the individual channels, or simply merge the multiple channels into one before VAD?

**Comment by AWAS666** [comment]
> Hi,
> 
> Thanks for raising the issue. In this case, would you like to perform VAD on the individual channels, or simply merge the multiple channels into one before VAD?

think that may depend on the use case, though I'd think merging them is good enough for most use cases, at least it's for mine.

**Comment by HolgerBovbjerg** [comment]
Alright, for now I think we will simply merge the channels into mono, leaving multichannel VAD for a future update if needed.
